### ISSUE TITLE
Missing model_state_dict_path

### ISSUE THREAD

**Issue by mndiosvax** [aryopg/vaxformer#4]
Hello

I'm trying to implement vaxformer in an AWS instance (ml.p3.2xlarge). I'm receiving the following error. Could you advise as to how to resolve the issue?

BW

Matthew

python scripts/train.py --config_filepath=configs/train/lstm_base.yaml 

/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_type" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_state_dict_path" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_configs" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
Traceback (most recent call last):
  File "/home/ec2-user/SageMaker/vaxformer/scripts/train.py", line 110, in <module>
    main()
  File "/home/ec2-user/SageMaker/vaxformer/scripts/train.py", line 33, in main
    configs = TrainingConfigs(**common_utils.load_yaml(args.config_filepath))
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/site-packages/pydantic/main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for TrainingConfigs
model_configs.model_state_dict_path
  Field required [type=missing, input_value={'model_type': 'lstm', 'h..._accumulation_step': 1}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing

**Comment by aryopg** [comment]
Hi @mndiosvax , sorry for getting back to you late. I just pushed a fix 368d6ec2e8465d902bbcd57a4b502469d3296459 that hopefully solves your problem. I forgot to assign a default value to an optional hyperparameter `model_state_dict_path`.

I'm closing the issue for now, but don't hesitate to re-open it if necessary.
